import type { ThemeConfig } from "./types";

export const themePresets: Record<string, ThemeConfig> = {
  default: {
    backgroundColor: "#f7f5f4",
    textColor: "#292d4c",
    headingColor: "#292d4c",
    buttonStyle: "filled",
    buttonColor: "#5f4dc5",
    buttonTextColor: "#ffffff",
    buttonRadius: "lg",
    fontFamily: "DM Sans",
    socialIconColor: "#5f4dc5",
    maxWidth: "sm",
    blockSpacing: "normal",
  },
  midnight: {
    backgroundColor: "#060818",
    textColor: "#e2e8f0",
    headingColor: "#e2e8f0",
    buttonStyle: "outline",
    buttonColor: "#7c6de0",
    buttonTextColor: "#ffffff",
    buttonRadius: "lg",
    fontFamily: "DM Sans",
    socialIconColor: "#7c6de0",
    maxWidth: "sm",
    blockSpacing: "normal",
  },
  forest: {
    backgroundColor: "#f0f4f0",
    textColor: "#1a2e1a",
    headingColor: "#1a2e1a",
    buttonStyle: "soft",
    buttonColor: "#2d6a2d",
    buttonTextColor: "#1a2e1a",
    buttonRadius: "md",
    fontFamily: "DM Sans",
    socialIconColor: "#2d6a2d",
    maxWidth: "sm",
    blockSpacing: "normal",
  },
  sunset: {
    backgroundColor: "#fef5ee",
    textColor: "#3d2c1e",
    headingColor: "#3d2c1e",
    buttonStyle: "filled",
    buttonColor: "#e85d04",
    buttonTextColor: "#ffffff",
    buttonRadius: "full",
    fontFamily: "Playfair Display",
    socialIconColor: "#e85d04",
    maxWidth: "sm",
    blockSpacing: "relaxed",
  },
  minimal: {
    backgroundColor: "#ffffff",
    textColor: "#000000",
    headingColor: "#000000",
    buttonStyle: "shadow",
    buttonColor: "#000000",
    buttonTextColor: "#ffffff",
    buttonRadius: "none",
    fontFamily: "Inter",
    socialIconColor: "#000000",
    maxWidth: "sm",
    blockSpacing: "normal",
  },
};

export const PRESET_NAMES = Object.keys(themePresets);
